name: Build & Push Backend

on:
  repository_dispatch:
    types: [trigger-backend-deploy]

env:
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    if: github.event.client_payload.branch == 'dev' || github.event.client_payload.branch == 'prd'
    name: Deploy to Docker (${{ github.event.client_payload.branch }})
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        id: vars
        run: |
          BRANCH="${{ github.event.client_payload.branch }}"
          if [ "$BRANCH" = "prd" ]; then
            echo "tag=prd" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-backend-buildx-${{ github.event.client_payload.branch }}
          restore-keys: |
            ${{ runner.os }}-backend-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t anthonyxw87/e-commerce-backend:${{ steps.vars.outputs.tag }} \
            --build-arg REACT_APP_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }} \
            --build-arg REACT_APP_API_AUDIENCE=${{ secrets.REACT_APP_API_AUDIENCE }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            ./backend \
            --push

      - name: Move new Docker cache into place
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
  mark-backend-deployment-complete:
    name: Mark Backend Deployment Complete
    runs-on: ubuntu-latest
    needs: build-and-push
    if: needs.build-and-push.result == 'success' && github.event.client_payload.branch == 'dev'
    steps:
      - name: Send Backend Deployment Completion Signal
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Backend deploy complete for branch: ${{ github.event.client_payload.branch }}"
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GH_TOKEN" \
          -d '{"event_type": "deployment-complete", "client_payload": { "component": "backend", "status": "success", "branch": "dev" }}'
