name: Build & Deploy Frontend

on:
  repository_dispatch:
    types: [trigger-frontend-deploy]

env:
  REPO_NAME: ${{ github.repository }}
  BUILD_DIR: ./frontend/build

jobs:
  build-and-push-to-docker:
    runs-on: ubuntu-latest
    name: Build & Push Docker (dev)
    if: github.event.client_payload.branch == 'dev'

    steps:
      - name: Set environment variables
        id: vars
        run: |
          BRANCH="${{ github.event.client_payload.branch }}"
          if [ "$BRANCH" = "prd" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-frontend-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-frontend-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t anthonyxw87/e-commerce-frontend:${{ steps.vars.outputs.tag }} \
            --build-arg REACT_APP_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }} \
            --build-arg REACT_APP_AUTH0_CLIENT_ID=${{ secrets.REACT_APP_AUTH0_CLIENT_ID_DEV }} \
            --build-arg REACT_APP_API_AUDIENCE=${{ secrets.REACT_APP_API_AUDIENCE }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            ./frontend \
            --push

      - name: Move new Docker cache into place
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy-to-netlify:
    runs-on: ubuntu-latest
    name: Deploy to Netlify (${{ github.event.client_payload.branch }})
    if: github.event.client_payload.branch == 'dev' || github.event.client_payload.branch == 'prd'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: 23.10.0
          cache: 'npm'

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@19.0.3

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install --package-lock-only
          npm ci

      - name: Build Project
        working-directory: ./frontend
        env:
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID_PRD }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_AUDIENCE }}
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          DEPLOY_CMD="netlify deploy --dir $BUILD_DIR --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }}"

          if [[ "${{ github.event.client_payload.branch }}" == "prd" ]]; then
            DEPLOY_CMD="$DEPLOY_CMD --prod"
          else
            DEPLOY_CMD="$DEPLOY_CMD --json > deploy_output.json"
          fi

          echo "Running: $DEPLOY_CMD"
          eval $DEPLOY_CMD

      - name: Show Preview URL (if preview)
        if: github.event.client_payload.branch == 'dev'
        run: |
          echo "Preview URL:"
          cat deploy_output.json | jq -r '.deploy_url'

  mark-frontend-deployment-complete:
    name: Mark Frontend Deployment Complete
    runs-on: ubuntu-latest
    needs: [build-and-push-to-docker, deploy-to-netlify]
    if: needs.build-and-push-to-docker.result == 'success' && needs.deploy-to-netlify.result == 'success' && github.event.client_payload.branch == 'dev'
    steps:
      - name: Send Frontend Deployment Completion Signal
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Frontend deploy complete for branch: ${{ github.event.client_payload.branch }}"
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GH_TOKEN" \
          -d '{"event_type": "deployment-complete", "client_payload": { "component": "frontend", "status": "success", "branch": "dev" }}'

